let number=[10,20,30,40,50];
number.push(60);
console.log(number);
console.log(number.unshift(5));
number.pop();
console.log(number);
number.shift();
console.log(number);
number.indexOf(30);
console.log(number);
number.includes(40);
console.log(number);
number.join();
console.log(number);
number.sort();
console.log(number);
number.reverse();
console.log(number);
